### ISSUE TITLE
Investigate Bugs on Front Verifier

### ISSUE THREAD

**Issue by jbesraa** [filecoin-project/filplus-registry#4]

**Comment by jbesraa** [comment]
https://github.com/keyko-io/filecoin-verifier-frontend/issues/847
https://github.com/keyko-io/filecoin-verifier-frontend/issues/846

**Comment by clriesco** [comment]
https://github.com/keyko-io/filecoin-verifier-frontend/issues/846 already solved. A bot in the staging environment interfered with the production environment
