### ISSUE TITLE
Integrate approval flow

### ISSUE THREAD

**Issue by jbesraa** [filecoin-project/filplus-registry#7]
when application state(under lifecycle property) is "Approval", button in application page should be "Approve" 
and when clicked on, you should hit `/application/{id}/approve` and also in the body include 
```{
	"request_id": "random request id",
	"signer": {
		"signing_address": "signing_address_here",
		"time_of_signature": "time_of_signature_here",
		"message_cid": "message_cid_here"
	}
}
```
 this will move the application to confirmed state

**Comment by clriesco** [comment]
Ready for review: https://github.com/filecoin-project/filplus-registry/pull/13
